---
title: "Map-canada"
output: html_document
---

```{r canada}
  library(leaflet)
  library(rgdal)
    
# If the .shp files (provinces) aren't already downloaded on your system, this command downloads them
  if (!file.exists("./polygons/ne_50m_admin_1_states_provinces_lakes/ne_50m_admin_1_states_provinces_lakes.dbf")){
    download.file(file.path('http://www.naturalearthdata.com/http/',
                            'www.naturalearthdata.com/download/50m/cultural',
                            'ne_50m_admin_1_states_provinces_lakes.zip'), 
                  f <- tempfile())
    unzip(f, exdir = "./polygons/ne_50m_admin_1_states_provinces_lakes")
    rm(f)
  }
  
  # Read the .shp files
  provinces <- readOGR("./polygons/ne_50m_admin_1_states_provinces_lakes", 'ne_50m_admin_1_states_provinces_lakes', encoding='UTF-8')
  
  clear <- "#F2EFE9"
  lineColor <- "#000000"
  hoverColor <- "red"
  lineWeight <- 0.5
  
  # Keep map static, set the view on Canada, add the provinces layer, shade the provinces later, add the pop-up annotations
  map <- leaflet() %>% 
    leaflet(options = leafletOptions(zoomControl = FALSE,
                                   minZoom = 3, maxZoom = 3,
                                   dragging = FALSE)) %>%
    addTiles() %>% 
    setView(-110.09, 62.7,  zoom = 3) %>% 
    addPolygons(data = subset(provinces, name %in% c("British Columbia", "Alberta", "Saskatchewan", "Manitoba", "Ontario", "Québec", "New Brunswick", "Prince Edward Island", "Nova Scotia", "Newfoundland and Labrador", "Yukon", "Northwest Territories", "Nunavut")),
                fillColor = clear,
                fillOpacity = 0.5,
                stroke = TRUE,
                weight = lineWeight,
                color = lineColor,
                highlightOptions = highlightOptions(fillColor = hoverColor, bringToFront = TRUE, sendToBack = TRUE),
                popup = "idk") %>%
  # Add the checklist
    addLayersControl(overlayGroups = c('idk',
                        'what',
                        'the',
                        'options',
                        'are'),
                        options = layersControlOptions(collapsed = FALSE),
                        position = 'topright')
map
```


```{r colour by life expectency}
  
   # Color by quantile
  map=leaflet(provinces)%>% addTiles()  %>% setView(-74.09, 45.7,  zoom = 3) %>%
    addPolygons( stroke = FALSE, fillOpacity = 0.5, smoothFactor = 0.5, color = ~colorQuantile("YlOrRd", POP2005)(POP2005) )
  map
  
  # Numeric palette
  map=leaflet(provinces)%>% addTiles()  %>% setView(-74.09, 45.7,  zoom = 3) %>%
    addPolygons( stroke = FALSE, fillOpacity = 0.5, smoothFactor = 0.5, color = ~colorNumeric("YlOrRd", POP2005)(POP2005) )
  map
  
  # Bin
  map=leaflet(provinces)%>% addTiles()  %>% setView(-74.09, 45.7,  zoom = 3) %>%
    addPolygons( stroke = FALSE, fillOpacity = 0.5, smoothFactor = 0.5, color = ~colorBin("YlOrRd", POP2005)(POP2005) )
  map
  
  ```